# Generated by Django 4.2.5 on 2023-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp_lists',
            name='file',
            field=models.FileField(upload_to='media/upload/'),
        ),
    ]
